package ai.hardtalk.source.legal

/**
 * Play / in-app privacy pointers. Full policy lives in docs/privacy-policy.md.
 * Swap [PRIVACY_POLICY_URL] to GitHub Pages (or FastAPI `/privacy`) once hosted.
 */
object LegalLinks {
    const val PRIVACY_POLICY_URL =
        "https://github.com/Ashishsingh009/HardTalkAI/blob/main/docs/privacy-policy.md"
    const val CONTACT_EMAIL = "hello@hardtalk.ai"
    const val CONTACT_FALLBACK_EMAIL = "aashish2k2@gmail.com"
    const val LAST_UPDATED = "19 September 2026"

    val SUMMARY =
        "HardTalkAI is a prototype career-coaching practice app (Coach Heather). " +
            "There are no accounts in this build. Typed practice sends your replies and " +
            "round history to the coaching API so we can score the turn and generate the " +
            "counterpart’s next line. On Android, an optional live call talks to the same " +
            "counterpart over OpenAI Realtime; microphone audio goes to OpenAI for that " +
            "call, then the transcript is scored on our server. Coach Heather is not on " +
            "the call — she recaps after hang-up. If the operator configured OpenAI, " +
            "typed counterpart replies are also generated by OpenAI; scores stay on our " +
            "server. We do not sell personal information, run ads, or take payments " +
            "(no RevenueCat yet). Chats are not written to a database in this prototype. " +
            "Contact $CONTACT_EMAIL, or $CONTACT_FALLBACK_EMAIL if that inbox is not " +
            "monitored yet."
}
