"""Optional AI-powered counterpart replies.

When ``OPENAI_API_KEY`` is set (and the ``openai`` package is installed), the
counterpart's reply is generated by an LLM in character for the scenario.
Otherwise the deterministic engine is used. Coaching scores/tips are always
computed locally by :mod:`app.engine`, so they stay fast, offline, and testable.
"""

from __future__ import annotations

import os

from .models import ChatTurn, Scenario

DEFAULT_MODEL = "gpt-4o-mini"


def is_ai_enabled() -> bool:
    return bool(os.getenv("OPENAI_API_KEY"))


def engine_name() -> str:
    return "openai" if is_ai_enabled() else "builtin"


def _system_prompt(scenario: Scenario, tone: str) -> str:
    tone_hint = {
        "warming": "You are becoming more receptive and collaborative.",
        "guarded": "You are defensive, guarded, and a little resistant.",
        "neutral": "You are listening and weighing what they said, non-committal.",
    }.get(tone, "")
    return (
        f"You are {scenario.persona.name}, {scenario.persona.role}. "
        f"You are role-playing the other side of a difficult conversation so the user can practice. "
        f"Scenario: {scenario.summary} "
        f"Your current disposition: {tone_hint} "
        "Stay fully in character. Reply with one to three natural, conversational sentences. "
        "Do not break character, do not give coaching or meta commentary."
    )


def generate_ai_reply(
    scenario: Scenario,
    history: list[ChatTurn],
    user_message: str,
    tone: str,
) -> str:
    """Generate an in-character reply via OpenAI. Raises on any failure."""
    from openai import OpenAI  # imported lazily so the app runs without the dep

    client = OpenAI()
    model = os.getenv("OPENAI_MODEL", DEFAULT_MODEL)

    messages: list[dict[str, str]] = [{"role": "system", "content": _system_prompt(scenario, tone)}]
    for turn in history:
        role = "assistant" if turn.role == "counterpart" else "user"
        messages.append({"role": role, "content": turn.content})
    messages.append({"role": "user", "content": user_message})

    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0.8,
        max_tokens=200,
    )
    content = response.choices[0].message.content or ""
    return content.strip()
